// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ApiTwitter
{
	public partial class TweetsViewTableView : UITableViewCell
    {

        public static readonly NSString Key = new NSString(nameof(TweetsViewTableView));


        #region propierties
        public string Tweet {
            get => lbltweet.Text;
            set => lbltweet.Text = value;
        }

        public string RetweetedCount {
            get => lblRetweed.Text;
            set => lblRetweed.Text = value;
        }
        /*
        public string UsuarioName {
            get => lblUsuario.Text;
            set => lblUsuario.Text = value;
        }
        */
        #endregion

		#region consttuctors
        public TweetsViewTableView(IntPtr handle) : base(handle)
        {
        }
		#endregion
	}
}
